### ISSUE TITLE
Error detected while processing function dispatch#quickfix_init 

### ISSUE THREAD

**Issue by chrisjohnson** [tpope/vim-dispatch#235] opened 2018-05-07 14:47 UTC
Using vim-grep which triggers search commands through vim-dispatch, I seem to intermittently get this error:

```
Error detected while processing function dispatch#quickfix_init[1]..<SNR>145_request[19]..<SNR>145_request:
line    9:
E716: Key not present in Dictionary: handler . '/' . dispatch#pid(s:makes[i]) ==# a:request
E15: Invalid expression: s:makes[i].handler . '/' . dispatch#pid(s:makes[i]) ==# a:request
Error detected while processing function <SNR>52_Grep:
line   12:
E171: Missing :endif
Press ENTER or type command to continue
```

I'm a little confused about what exactly is causing this, hoping you might be able to shed some light. In previous versions of vim-dispatch, the way vim-grep calls vim-dispatch has worked fine, but since bumping to an updated version this error has started happening

**Comment by tpope** [comment] 2018-05-07 18:10
What is vim-grep?

**Comment by chrisjohnson** [comment] 2018-05-07 18:32
Oh sorry, I suppose context helps. I inherited ownership of it from https://github.com/teoljungberg/vim-grep

It basically just sets makeprg and errorformat to be one of several grep commands and their respective formats, and runs `:Make`, see code here: https://github.com/chrisjohnson/vim-grep/blob/master/plugin/grep.vim#L54-L67

**Comment by tpope** [comment] 2018-05-07 18:35
I just wanted to make sure nothing was using an internal API.

What adapter is in use when the error happens?

**Comment by tpope** [comment] 2018-05-07 18:38
Is the quickfix window title set? If so, what to?

**Comment by chrisjohnson** [comment] 2018-05-07 18:44
It doesn't use an existing compiler, since the idea is that each call to this function may warrant a different grep command (though maybe that's a bad approach?). It just sets `makeprg` and `errorformat` and then calls `:Make` with no arguments.

After a successful non-error run of this command, the quickfix title is set to eg `:Dispatch rg --vimgrep --color=never --no-heading --hidden "\bPROGRAM_OPT_OUTS\b" . (tmux/45797)`

Does that answer your questions?

**Comment by tpope** [comment] 2018-05-07 18:53
The answer is `tmux`, based on the quickfix title.

The next time this happens, try cracking open `autoload/dispatch.vim`, adding `let g:makes = s:makes`, and then looking at `g:makes`. Does it have any entries without a `handler` key? Does anything else about them look suspicious? Maybe some other plugin is doing something it shouldn't. If that's the problem we can guard against it, but I'm worried it's something in dispatch.vim doing it.

As for which *compiler* you are using, it shouldn't affect this, but if you don't want to use a proper compiler plugin, you should set `b:current_compiler` too. Here's a snippet I use:

```vim
let saved = [get(b:, 'current_compiler', ''), &l:mp, &l:efm]
try
  execute (exists(':Make') == 2 ? 'Make' : 'make!')
finally
  let [b:current_compiler, &l:mp, &l:efm] = saved
  if empty(saved[0]) | unlet! b:current_compiler | endif
endtry
```

**Comment by chrisjohnson** [comment] 2018-05-07 19:07
As I research more into vim compilers, I'm not convinced setting them is the way to go, since this is more of a command-driven thing, not a file-type driven thing. As long as setting makeprg and errorformat directly doesn't scream bad behavior to you, I'm inclined to stick with that approach.

I tried what you suggested, directly after [this line](https://github.com/tpope/vim-dispatch/blob/ca88fd7bd3d58620c7bfd604e3ebfa71b9c5001d/autoload/dispatch.vim#L703) in `autoload/dispatch.vim` I added `let g:makes = s:makes` and then after reproducing the error above, checked its contents. I have two entries which are as follows:

```
[
  {
    "pid": 53609,
    "background": 0,
    "action": "make",
    "program": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "compiler": "rspec",
    "command": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "file": "\/var\/folders\/g6\/b_b0kcns13z9smpz5kk2j8d9wsd9c2\/T\/vTSayIX\/211",
    "id": 1,
    "handler": "tmux",
    "completed": 1,
    "format": "%f:%l:%c:%m,%f:%l:%m",
    "directory": "\/Users\/cjohnson\/vagrant\/code\/clinical-alerts-docker\/clinical-alerts-api",
    "expanded": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "title": "rspec",
    "args": ""
  },
  {
    "file": "\/var\/folders\/g6\/b_b0kcns13z9smpz5kk2j8d9wsd9c2\/T\/vTSayIX\/226",
    "directory": "\/Users\/cjohnson\/vagrant\/code\/clinical-alerts-docker\/clinical-alerts-api",
    "id": 2,
    "compiler": "rspec",
    "background": 0,
    "format": "%f:%l:%c:%m,%f:%l:%m",
    "action": "make",
    "expanded": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "program": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "command": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "title": "rspec",
    "args": ""
  }
]
```

As you suspected, one of the entries is missing a `handler` key

**Comment by tpope** [comment] 2018-05-07 20:07
Yep, that's the problem, and there's no obvious other plugin to blame it on.

So [the request is added to `s:makes`](https://github.com/tpope/vim-dispatch/blob/e4828f2ecd0ed847599763524d029eff6e79aac5/autoload/dispatch.vim#L703-L709) very slightly before the [handler is assigned to the request](https://github.com/tpope/vim-dispatch/blob/e4828f2ecd0ed847599763524d029eff6e79aac5/autoload/dispatch.vim#L278). If the `VimResized` event triggers in the gap things could definitely go south. But I'm pretty sure `VimResized` doesn't interrupt running code, and even if it did, the timing would be ridiculously tight, as the external command is bundled with a 0.1 second sleep to avoid race conditions.

I pushed up a change to prevent this particular error message, but I don't think it actually solves the problem. Keep an eye out for further issues.

**Comment by chrisjohnson** [comment] 2018-05-07 21:43
No dice, I'm still getting pretty much the same error:

```
Error detected while processing function dispatch#quickfix_init[1]..<SNR>143_request[19]..<SNR>143_request:
line    9:
E716: Key not present in Dictionary: handler . '/' . dispatch#pid(s:makes[i]) ==# a:request
E15: Invalid expression: s:makes[i].handler . '/' . dispatch#pid(s:makes[i]) ==# a:request
Error detected while processing function <SNR>52_Grep:
line   12:
E171: Missing :endif
```

And the output of `g:makes` is:

```
[
  {
    "pid": 10374,
    "background": 0,
    "action": "make",
    "program": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "compiler": "rspec",
    "command": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "file": "\/var\/folders\/g6\/b_b0kcns13z9smpz5kk2j8d9wsd9c2\/T\/vKvABuk\/215",
    "id": 1,
    "handler": "tmux",
    "completed": 1,
    "format": "%f:%l:%c:%m,%f:%l:%m",
    "directory": "\/Users\/cjohnson\/vagrant\/code\/clinical-alerts-docker\/clinical-alerts-api",
    "expanded": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "title": "rspec",
    "args": ""
  },
  {
    "pid": 10403,
    "background": 0,
    "action": "make",
    "program": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "compiler": "rspec",
    "command": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "file": "\/var\/folders\/g6\/b_b0kcns13z9smpz5kk2j8d9wsd9c2\/T\/vKvABuk\/228",
    "id": 2,
    "handler": "tmux",
    "completed": 1,
    "format": "%f:%l:%c:%m,%f:%l:%m",
    "directory": "\/Users\/cjohnson\/vagrant\/code\/clinical-alerts-docker\/clinical-alerts-api",
    "expanded": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "title": "rspec",
    "args": ""
  },
  {
    "file": "\/var\/folders\/g6\/b_b0kcns13z9smpz5kk2j8d9wsd9c2\/T\/vKvABuk\/242",
    "directory": "\/Users\/cjohnson\/vagrant\/code\/clinical-alerts-docker\/clinical-alerts-api",
    "id": 3,
    "compiler": "rspec",
    "background": 0,
    "format": "%f:%l:%c:%m,%f:%l:%m",
    "action": "make",
    "expanded": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "program": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "command": "rg --vimgrep --color=never --no-heading --hidden \"\bPROGRAM_OPT_OUTS\b\" .",
    "title": "rspec",
    "args": ""
  }
]
```

The quickfix window does seem to come up with the right output so I think at least hiding the error would improve the experience, even if it doesn't fix the underlying issue, but sadly even on latest commit I still see the above error

**Comment by tpope** [comment] 2018-05-07 21:55
My fix was based on misreading the stacktrace. I'll figure out something else.

Are you able to reproduce this consistently enough that you'd have any chance of bisecting your way to the commit that broke things? That would almost certainly reveal the problem.

**Comment by chrisjohnson** [comment] 2018-05-07 22:00
I get it about one in three calls, so I will give it a try

**Comment by chrisjohnson** [comment] 2018-05-07 22:32
Sadly, I bisected between what was known to be working and the latest commit and was not able to find one single working commit. Even after going back to the version I had been using for quite some time I couldn't get good behavior anymore. So I destroyed my vim session and started over and the behavior isn't present, even on latest master. I'm not sure exactly what in the session would have messed with this, I confirmed nothing in the session was setting the `makes` variable so I don't quite get it. Anyway, it seems that the problem has vanished since then, so unless I rediscover it as part of a new session I think it's safe to close this. Sorry for the confusion

**Comment by tpope** [comment] 2018-05-07 23:39
For future reference, is this a session as in `:mksession`? Strange if true.

**Comment by chrisjohnson** [comment] 2018-05-08 00:32
It's via `vim-session` which I'm pretty sure uses mksession yes

**Comment by tpope** [comment] 2018-05-13 21:06
Grep your plugins for `dispatch#` to see if you have any using internal APIs. That's the main thing I'd like to rule out.

**Comment by chrisjohnson** [comment] 2018-05-13 21:13
`rgrep 'dispatch#' ~/.vim | grep -v 'vim-dispatch'` yielded no results, nothing outside of vim-dispatch is using any `dispatch#` calls

**Comment by tpope** [comment] 2018-05-13 21:28
Can you try changing the `perl -e "select(undef,undef,undef,0.1)"` to a full 1 second and see if the issue continues?

**Comment by chrisjohnson** [comment] 2018-05-14 21:09
@tpope After changing from 0.1 to 1, there is obviously a delay in the response, but I do not get the error and everything behaves as expected.

**Comment by tpope** [comment] 2018-05-14 21:40
Well, that suggests a race condition. Try `0.2`?

**Comment by chrisjohnson** [comment] 2018-05-15 13:49
Yep `0.2` is playing a lot better here. And just because I was curious, I put the `s:makes` debug line back in and checked it after each run, and every make had a properly filled in `handler`

**Comment by tpope** [comment] 2018-05-16 07:03
Okay one more thing, try putting in a `sync;` before the `perl` and see if that gets it to go away too. `sync` will take longer when the system is bogged down so it's nice for something like this.

**Closed** 2018-05-18 22:35 UTC

**Comment by chrisjohnson** [comment] 2018-05-18 23:15
Thank you much!

**Comment by mark2185** [comment] 2021-04-17 09:31
I hit the same error yesterday with `tmux` and `iTerm2`, the `handler` key is missing. The plugin I'm using is only calling `Make`, nothing else internal.

The file it is trying to read does actually exist, but the exception is thrown because of the missing key. I tried increasing the `sleep` time like suggested, but to no avail. (I don't know if that's even related, but tried it anyway).

What else can I do?

**Comment by tpope** [comment] 2021-04-17 15:30
It might be the same error message but it's not the same error because the code has changed. What's the stacktrace?

By increasing the sleep time, do you mean increasing the 0.1 in the Perl `select`, or something else?

**Comment by mark2185** [comment] 2021-04-17 15:43
This is the stack trace:
```
Error detected while processing function <lambda>2[1]..dispatch#complete[14]..<SNR>84_cwindow[1]..<SNR>84_cgetfile[5]..
function <lambda>2[1]..dispatch#complete[14]..<SNR>84_cwindow[1]..<SNR>84_cgetfile:
line    5:
E605: Exception not caught: Bad request {'file': '/var/folders/35/k9r5p9ss7tld90dpf9xnqq740000gn/T/vkHAAD3/7', 'title':
 'make', 'id': 1, 'background': 0, 'format': ' %#%f:%l %#(%m),See also "%f".,%E%>CMake Error at %f:%l:,%Z  %m,%E%>CMake
 Error at %f:%l (%[%^)]%#):,%Z  %m,%W%>Cmake Deprecation Warning at %f:%l (%[%^)]%#):,%Z  %m,%W%>Cmake Warning at %f:%l
 (%[%^)]%#):,%Z  %m,%E%>CMake Error: Error in cmake code at,%C%>%f:%l:,%Z%m,%E%>CMake Error in %.%#:,%C%>  %m,%C%>,%C%>
    %f:%l (if),%C%>,%Z  %m,', 'action': 'make', 'expanded': 'cmake -DCMAKE_BUILD_TYPE=Debug -G "Ninja" -DCMAKE_C_COMPIL
ER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_RUNTIME_CHECKS=ON -
DMB_TREAT_WARNINGS_AS_ERRORS=OFF   -B /Users/mark/workspace/build/core-utils/clang/debug -S /Users/mark/workspace/gits/
core-utils', 'program': 'cmake -DCMAKE_BUILD_TYPE=Debug -G "Ninja" -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPIL
ER=/usr/bin/clang++ -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_RUNTIME_
Error detected while processing function <lambda>2[1]..dispatch#complete:
line   14:
E171: Missing :endif
```

And I've put an `echom` in [this if](https://github.com/tpope/vim-dispatch/blob/4313cbb398d8b61b08be09f9b5a9ae4270c86004/autoload/dispatch.vim#L1289) and the message is printed, so I presume that's the exception that breaks it.

>By increasing the sleep time, do you mean increasing the 0.1 in the Perl select

Yes.

**Comment by mark2185** [comment] 2021-04-17 16:48
You know what, I just tried `tmux kill-server` and it completed _unsuccessfully._ 

I had to `kill -9` it and when I started it up again, it worked. Sorry for bothering.
